spring:
  application:
    name: ae1473exam1

  datasource:
    url: jdbc:h2:mem:booksdb
    driver-class-name: org.h2.Driver
    username: josu
    password: josu

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080